### ISSUE TITLE
Certificate invalid for ipv6.ifconfig.es

### ISSUE THREAD

**Issue by cions** [dcarrillo/whatismyip#23]
```
$ curl https://ipv6.ifconfig.es/
curl: (60) SSL: no alternative certificate subject name matches target host name 'ipv6.ifconfig.es'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Currently SAN includes ipv4.ifconfig.es but not ipv6.ifconfig.es
```
X509v3 Subject Alternative Name:
    DNS:ifconfig.es, DNS:ipv4.ifconfig.es, DNS:www.ifconfig.es
```

**Comment by dcarrillo** [comment]
Hi,

Thank you for notifying me about that. Actually, the `ipv4` and `ipv6` DNS entries are undocumented and should be removed. Honestly, I forgot about them. 

If you need to force ipv6, you can make a request with `curl -6 https://ifconfig.es`. However, if you think the explicit entries are useful, I can add the missing SAN to the certificate and keep the feature.

**Comment by cions** [comment]
Although many command-line apps has `-[46]` option, HTTP client in scripting languages (Node.js `fetch()`, Python `urllib.request.urlopen()`, etc.) have no way to force IPv4/6.

So I think {ipv4,ipv6}.ifconfig.es is useful and should be an official feature.

**Comment by dcarrillo** [comment]
Ok, I've added the missing SAN, thank you for your report.
